Update TopicDescription.java
Lack of NoArg default constructor leads to exception listed below.

As a workaround (WA) I had to manually update the TopicDescription by adding the default constructor for inner class AuthorizationRulesWrapper.
With WA in place, communication is working as expected.
Otherwise app (using 7.7.0) is unable to do perform any Topic related actions (like: Admin.getTopic(), create sub, receive/send msgs).

Issue is actual for versions from (7.0.2 to 7.7.0).
My app is using ConnectionStrings for auth.

Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.azure.messaging.servicebus.implementation.models.TopicDescription$AuthorizationRulesWrapper` (although at least one Creator exists): no default no-arguments constructor found
 at [Source: (StringReader); line: 1, column: 1142] (through reference chain: com.azure.messaging.servicebus.implementation.models.TopicDescriptionEntry["content"]->com.azure.messaging.servicebus.implementation.models.TopicDescriptionEntryContent["TopicDescription"]->com.azure.messaging.servicebus.implementation.models.TopicDescription["AuthorizationRules"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1728)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1353)

Full stacktrace has the following block. I'll skip several lines for clarity.

java.lang.RuntimeException: Exception while deserializing. Body: [<entry xmlns="http://www.w3.org/2005/Atom">
.............
<AuthorizationRules></AuthorizationRules>
.............
</entry>]. Class: class com.azure.messaging.servicebus.implementation.models.TopicDescriptionEntry
	at com.azure.messaging.servicebus.administration.ServiceBusAdministrationAsyncClient.deserialize(ServiceBusAdministrationAsyncClient.java:2305)