Cosmos DB CosmosContainer#getFeedRanges bugfix on Container deletion recreation with the same name (#25523)
If a CosmosContainer is deleted and recreated with the same name, `CosmosContainer#getFeedRanges()` API doesn't internally refresh the naming cache resulting in a failure.

This PR ensures upon such scenario `CosmosContainer#getFeedRanges` does a proper cache refresh.

This API is used in Cosmos DB spark connector and the presence of this bug results in similar scenario failure on the spark side as well:

https://portal.microsofticm.com/imp/v3/incidents/details/272636592/home

```bash
java.lang.IllegalStateException: PartitionKeyRange list cannot be null at 
azure_cosmos_spark.com.azure.cosmos.implementation.RxDocumentClientImpl.toFeedRanges(RxDocumentClientImpl.java:4124) 
```