[Patch-Release] Fix patch release pipeline failures (#39361)
* processing pomFile=/mnt/vss/_work/1/s/sdk/webpubsub/azure-messaging-webpubsub-client/pom.xml
Error: {x-version-update;com.azure:azure-messaging-webpubsub;dependency} is incorrectly set to dependency. Libraries building and releasing as part of the same pipeline need to be using the current versions of each other.
processing pomFile=/mnt/vss/_work/1/s/sdk/identity/azure-identity-extensions/pom.xml
Error: {x-version-update;com.azure:azure-identity;dependency} is incorrectly set to dependency. Libraries building and releasing as part of the same pipeline need to be using the current versions of each other.
processing pomFile=/mnt/vss/_work/1/s/sdk/keyvault/azure-security-keyvault-administration/pom.xml
Error: {x-version-update;com.azure:azure-security-keyvault-keys;dependency} is incorrectly set to dependency. Libraries building and releasing as part of the same pipeline need to be using the current versions of each other.
There were errors encountered during execution. Please fix errors and run the script again.

* [debug]Extracting entries from [/mnt/vss/_work/1/s/sdk/identity/azure-identity/CHANGELOG.md].
Found the following change log entry for version '1.11.4' in [/mnt/vss/_work/1/s/sdk/identity/azure-identity/CHANGELOG.md].
-----
## 1.11.4 (2024-03-14)

-----
[debug]Verifying as a release build because the changelog entry has a valid date.
##[error]Invalid date [ 2024-03-14 ]. The date for the changelog being released must be the latest in the file.