Fix #31716. NoClassDefFoundError. (#31800)
* Fix #31716. NoClassDefFoundError.

* Make UserPrincipalManager#getRoles more robust.

* Fix pipeline failure caused by cspell.json.